"""Pydantic request/response schemas for the API."""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from enum import Enum


class DiseaseCategory(str, Enum):
    ALZHEIMER = "alzheimer"
    EYE_DISEASE = "eye_disease"
    HEART_FAILURE = "heart_failure"
    SYMPTOM_PREDICTION = "symptom_prediction"
    PARKINSONS = "parkinsons"
    HEART_DISEASE = "heart_disease"


class HeartFailureInput(BaseModel):
    age: float = Field(..., ge=1, le=120)
    anaemia: int = Field(..., ge=0, le=1)
    creatinine_phosphokinase: float = Field(..., ge=1)
    diabetes: int = Field(..., ge=0, le=1)
    ejection_fraction: float = Field(..., ge=1, le=100)
    high_blood_pressure: int = Field(..., ge=0, le=1)
    platelets: float = Field(..., ge=1)
    serum_creatinine: float = Field(..., ge=0.1)
    serum_sodium: float = Field(..., ge=100, le=160)
    sex: int = Field(..., ge=0, le=1)
    smoking: int = Field(..., ge=0, le=1)
    time: int = Field(..., ge=1, le=365)


class ParkinsonInput(BaseModel):
    fo: float = Field(..., alias="MDVP:Fo(Hz)")
    fhi: float = Field(..., alias="MDVP:Fhi(Hz)")
    flo: float = Field(..., alias="MDVP:Flo(Hz)")
    jitter_percent: float = Field(..., alias="MDVP:Jitter(%)")
    jitter_abs: float = Field(..., alias="MDVP:Jitter(Abs)")
    rap: float = Field(..., alias="MDVP:RAP")
    ppq: float = Field(..., alias="MDVP:PPQ")
    ddp: float = Field(..., alias="Jitter:DDP")
    shimmer: float = Field(..., alias="MDVP:Shimmer")
    shimmer_db: float = Field(..., alias="MDVP:Shimmer(dB)")
    apq3: float = Field(..., alias="Shimmer:APQ3")
    apq5: float = Field(..., alias="Shimmer:APQ5")
    apq: float = Field(..., alias="MDVP:APQ")
    dda: float = Field(..., alias="Shimmer:DDA")
    nhr: float = Field(..., alias="NHR")
    hnr: float = Field(..., alias="HNR")
    rpde: float = Field(..., alias="RPDE")
    dfa: float = Field(..., alias="DFA")
    spread1: float = Field(..., alias="spread1")
    spread2: float = Field(..., alias="spread2")
    d2: float = Field(..., alias="D2")
    ppe: float = Field(..., alias="PPE")

    class Config:
        populate_by_name = True


class HeartDiseaseInput(BaseModel):
    age: float
    sex: int
    cp: int
    trestbps: float
    chol: float
    fbs: int
    restecg: int
    thalach: float
    exang: int
    oldpeak: float
    slope: int
    ca: int
    thal: int


class SymptomInput(BaseModel):
    symptoms: List[str] = Field(..., min_length=1)


class SeverityLevel(BaseModel):
    level: str
    label: str
    color: str
    confidence: Optional[float] = None


class AnalysisResult(BaseModel):
    disease_category: str
    prediction: str
    prediction_label: str
    confidence: float
    severity: SeverityLevel
    summary: str
    details: Optional[Dict[str, Any]] = None
    disclaimer: str = (
        "⚠️ DISCLAIMER: This analysis is generated by an AI system and is intended "
        "for informational and decision-support purposes only. It does NOT constitute "
        "a medical diagnosis. Please consult a qualified healthcare professional for "
        "proper medical advice, diagnosis, and treatment."
    )


class HospitalInfo(BaseModel):
    name: str
    address: str
    city: Optional[str] = None
    latitude: float
    longitude: float
    distance_km: float
    specialties: List[str]
    phone: Optional[str] = None
    rating: Optional[float] = None


class HospitalRequest(BaseModel):
    latitude: float
    longitude: float
    disease_category: str
    radius_km: float = 50.0


class HospitalResponse(BaseModel):
    hospitals: List[HospitalInfo]
    search_radius_km: float
    total_found: int
    source: str  # "overpass_api" or "local_database"
